// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK3-d8SbF_mGZOL1DWscrhTvRfJk7RjSU',
    appId: '1:828313183999:web:1e3b8c8f4e4d091f2bceca',
    messagingSenderId: '828313183999',
    projectId: 'e-commerce-app-29bb4',
    authDomain: 'e-commerce-app-29bb4.firebaseapp.com',
    storageBucket: 'e-commerce-app-29bb4.firebasestorage.app',
    measurementId: 'G-V58Z1QN8SE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvOZI0DV67QM2ukxbUM9Y0_IYBobFKq7A',
    appId: '1:828313183999:android:26174b397c78058e2bceca',
    messagingSenderId: '828313183999',
    projectId: 'e-commerce-app-29bb4',
    storageBucket: 'e-commerce-app-29bb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXBBFbdBgVYdhf20VH_g-NcDnSs5ieh-I',
    appId: '1:828313183999:ios:0cc5ad8de40aad9b2bceca',
    messagingSenderId: '828313183999',
    projectId: 'e-commerce-app-29bb4',
    storageBucket: 'e-commerce-app-29bb4.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXBBFbdBgVYdhf20VH_g-NcDnSs5ieh-I',
    appId: '1:828313183999:ios:0cc5ad8de40aad9b2bceca',
    messagingSenderId: '828313183999',
    projectId: 'e-commerce-app-29bb4',
    storageBucket: 'e-commerce-app-29bb4.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK3-d8SbF_mGZOL1DWscrhTvRfJk7RjSU',
    appId: '1:828313183999:web:4dc9caa96fdebf112bceca',
    messagingSenderId: '828313183999',
    projectId: 'e-commerce-app-29bb4',
    authDomain: 'e-commerce-app-29bb4.firebaseapp.com',
    storageBucket: 'e-commerce-app-29bb4.firebasestorage.app',
    measurementId: 'G-JKGJFH8W9X',
  );
}
